### ISSUE TITLE
unable to load numpy_formathandler accelerator from OpenGL_accelerate

### ISSUE THREAD

**Issue by alex4727** [alievk/npbg#13]
Hi, currently testing the code with sample data but there seems to be an error loading numpy_formathandler accelerator. 
After calling python viewer.py --config downloads/person_1.yaml --viewport 2000,1328 --origin-view, the view.py window freezes with above error.
I can't figure out what's wrong here. Any idea? 
Thanks!

![Screenshot from 2020-12-31 04-22-42](https://user-images.githubusercontent.com/60963841/103376413-e8fe9580-4b1f-11eb-9c32-1654b5a9696a.png)

**Comment by seva100** [comment]
Actually we have the same debug message when running viewer.py, but it does
not affect the rendering. The viewer is still able to run successfully with
this message.

Try to press the "Wait" button and to see if it helps.

ср, 30 дек. 2020 г., 22:23 alex4727 <notifications@github.com>:

**Comment by alex4727** [comment]
I'm currently using Nvidia rtx 3070 graphics card which is known to be have similar performance compared to RTX2080 which is at least a bit better than recommended gpu (1080ti). How long does it take for typical gpu to work on this sample dataset?

**Comment by seva100** [comment]
For the "person1" dataset and ~FullHD resolution, `viewer.py` operates at ~4 FPS on 1080ti on my end. Do you observe worse performance? If FPS is low, decreasing resolution in `--viewport` should help.

**Comment by alex4727** [comment]
Thanks for answering:)
After running viewer.py and pushing "Wait" button, viewer stays black for about 10~15minute and ends up with the following error. I'm currently using cuda version 11.1, cudnn 8, and tf-nightly build (it's only option for rtx30 series for now). 
cuDNN error: CUDNN_STATUS_EXECUTION_FAILED does look like a version-related problem,, but can't easily figure out how to solve..! Any ideas about the following error? Thanks for help!


(npbg) alex@alex-System-Product-Name:~/Downloads/npbg-master$ python viewer.py --config downloads/person_1.yaml --viewport 2000,1328 --origin-view
loading pointcloud...
=== 3D model ===
VERTICES:  3072078
EXTENT:  [-16.5258255  -14.02860832 -30.76384926] [ 10.81384468   2.03398347 -20.07631493]
================
new viewport size  (2000, 1328)
[i] HiDPI detected, fixing window size
Unable to load numpy_formathandler accelerator from OpenGL_accelerate
[i] Using GLFW (GL 4.6)
Net checkpoint: downloads/scenes/person_1/02-20_08-42-55/UNet_stage_0_epoch_39_net.pth
Texture checkpoint: downloads/scenes/person_1/02-20_08-42-55/PointTexture_stage_0_epoch_39.pth
SUPERSAMPLING: 2
[i] Running at 60 frames/second
on_resize 1853x1025
Traceback (most recent call last):
  File "viewer.py", line 435, in <module>
    my_app.run()
  File "viewer.py", line 248, in run
    app.run()
  File "/home/alex/anaconda3/envs/npbg/lib/python3.6/site-packages/glumpy/app/__init__.py", line 317, in run
    clock = __init__(clock=clock, framerate=framerate, backend=__backend__)
  File "/home/alex/anaconda3/envs/npbg/lib/python3.6/site-packages/glumpy/app/__init__.py", line 277, in __init__
    window.dispatch_event('on_resize', window._width, window._height)
  File "/home/alex/anaconda3/envs/npbg/lib/python3.6/site-packages/glumpy/app/window/event.py", line 396, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/home/alex/anaconda3/envs/npbg/lib/python3.6/site-packages/glumpy/app/window/window.py", line 221, in on_resize
    self.dispatch_event('on_draw', 0.0)
  File "/home/alex/anaconda3/envs/npbg/lib/python3.6/site-packages/glumpy/app/window/event.py", line 386, in dispatch_event
    if handler(*args):
  File "viewer.py", line 358, in on_draw
    self.last_frame = self.render_frame(self.last_view_matrix)
  File "viewer.py", line 254, in render_frame
    frame = self.model.infer()['output'].flip([0])
  File "/home/alex/Downloads/npbg-master/npbg/gl/nn.py", line 121, in infer
    out, net_input = self.model(input_dict, return_input=True)
  File "/home/alex/anaconda3/envs/npbg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/alex/Downloads/npbg-master/npbg/models/compose.py", line 194, in forward
    out1 = self.net(*input_multiscale, **kwargs)
  File "/home/alex/anaconda3/envs/npbg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/alex/Downloads/npbg-master/npbg/models/unet.py", line 230, in forward
    in64 = self.start(inputs[0], mask=masks[0])
  File "/home/alex/anaconda3/envs/npbg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/alex/Downloads/npbg-master/npbg/models/unet.py", line 77, in forward
    features = self.block.act_f(self.block.conv_f(x))
  File "/home/alex/anaconda3/envs/npbg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/alex/anaconda3/envs/npbg/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/alex/anaconda3/envs/npbg/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
deleting buffers...
