### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by Shubhendu-Jena** [alievk/npbg#25]
Hi,

Thanks for your great work! I tried training the network from scratch and despite my best efforts, a bug seems to persist on my side. It seems the in render.py (/npbg/npbg/gl/render.py), lines 53 and 83 (self.fbo.activate() and self.fbo.deactivate() respectively) seem to create a problem. I get the following error : 

 File "/media/shubhendujena/3E08E5152BF3ABC4/nvs_experiments/npbg_try/npbg/gl/render.py", line 54, in render
    self.fbo.activate()
  File "/home/shubhendujena/anaconda3/envs/npbg/lib/python3.6/site-packages/glumpy/gloo/globject.py", line 95, in activate
    self._activate()
  File "/home/shubhendujena/anaconda3/envs/npbg/lib/python3.6/site-packages/glumpy/gloo/framebuffer.py", line 375, in _activate
    gl.glBindFramebuffer(gl.GL_FRAMEBUFFER, self._handle)
  File "src/errorchecker.pyx", line 53, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glBindFramebuffer,
        cArguments = (GL_FRAMEBUFFER, 1)
)
deleting buffers...
Exception ignored in: <bound method NNScene.__del__ of <npbg.gl.programs.NNScene object at 0x7f19b91bac18>>
Traceback (most recent call last):
  File "/media/shubhendujena/3E08E5152BF3ABC4/nvs_experiments/npbg_try/npbg/gl/programs.py", line 287, in __del__
  File "/media/shubhendujena/3E08E5152BF3ABC4/nvs_experiments/npbg_try/npbg/gl/programs.py", line 292, in delete
  File "src/latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 311, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "/home/shubhendujena/anaconda3/envs/npbg/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 401, in __call__
  File "/home/shubhendujena/anaconda3/envs/npbg/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 381, in load
ImportError: sys.meta_path is None, Python is likely shutting down
deleting buffers...
Exception ignored in: <bound method NNScene.__del__ of <npbg.gl.programs.NNScene object at 0x7f19b922c908>>
Traceback (most recent call last):
  File "/media/shubhendujena/3E08E5152BF3ABC4/nvs_experiments/npbg_try/npbg/gl/programs.py", line 287, in __del__
  File "/media/shubhendujena/3E08E5152BF3ABC4/nvs_experiments/npbg_try/npbg/gl/programs.py", line 292, in delete
  File "src/latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 311, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "/home/shubhendujena/anaconda3/envs/npbg/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 401, in __call__
  File "/home/shubhendujena/anaconda3/envs/npbg/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 381, in load
ImportError: sys.meta_path is None, Python is likely shutting down
deleting buffers...
Exception ignored in: <bound method NNScene.__del__ of <npbg.gl.programs.NNScene object at 0x7f19b922c048>>
Traceback (most recent call last):
  File "/media/shubhendujena/3E08E5152BF3ABC4/nvs_experiments/npbg_try/npbg/gl/programs.py", line 287, in __del__
  File "/media/shubhendujena/3E08E5152BF3ABC4/nvs_experiments/npbg_try/npbg/gl/programs.py", line 292, in delete
  File "src/latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 311, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "/home/shubhendujena/anaconda3/envs/npbg/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 401, in __call__
  File "/home/shubhendujena/anaconda3/envs/npbg/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 381, in load
ImportError: sys.meta_path is None, Python is likely shutting down
deleting buffers...
Exception ignored in: <bound method NNScene.__del__ of <npbg.gl.programs.NNScene object at 0x7f19b91d4f28>>
Traceback (most recent call last):
  File "/media/shubhendujena/3E08E5152BF3ABC4/nvs_experiments/npbg_try/npbg/gl/programs.py", line 287, in __del__
  File "/media/shubhendujena/3E08E5152BF3ABC4/nvs_experiments/npbg_try/npbg/gl/programs.py", line 292, in delete
  File "src/latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 311, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "/home/shubhendujena/anaconda3/envs/npbg/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 401, in __call__
  File "/home/shubhendujena/anaconda3/envs/npbg/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 381, in load
ImportError: sys.meta_path is None, Python is likely shutting down

It goes away if I comment out these lines but then I get a bunch of windows opening every few steps. I'd be grateful if you could give me some tips on how I can go about resolving this.

Thanks in advance

**Comment by seva100** [comment]
Hi @Shubhendu-Jena, thanks for appreciating our work!
We have never stumped upon such an exception unfortunately. Based on what I've been able to google about it, you might want to try adding some `time.sleep(...)` calls in the end of the program or before the important lines of code.

**Comment by Shubhendu-Jena** [comment]
Hi @seva100, thanks for the quick response. While adding **time.sleep(...)** didn't solve the problem, I followed this (https://stackoverflow.com/questions/51918633/importerror-failed-to-load-glfw3-shared-library-without-root-access-on-linux) and it solved the issue. Thanks again.
